### PR TITLE
added readme.md

### PR DESCRIPTION
**Pull request by ayushsarode**

### CODE REVIEW

**Comment by ayushsarode** [comment]
please can you label it as hacktiberfest-accepted?

**Comment by neutr0ncodes** [comment]
Hey @AyushSarode please add some content related to the project in the readme file

**Comment by ayushsarode** [comment]
> Hey @AyushSarode please add some content related to the project in the readme file
Sure I'm on it.

**Review by ayushsarode — COMMENTED** [review]
I edited readme.md .
Please add hacktoberfest-accepted label.
Thank you!

**Comment by neutr0ncodes** [comment]
Yep added thanks for the help

**Comment by ayushsarode** [comment]
hey buddy!! you didn't add hacktoberfest-accept label

**Comment by neutr0ncodes** [comment]
added it

**Comment by ayushsarode** [comment]
Please can you tell me why it's not participating?

Screenshot 2022-10-02 235651

**Pull request merged**
